# Generated by Django 5.2.8 on 2025-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions', '0002_alter_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
